# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_description', models.CharField(max_length=700)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
